Correctly detect the project runtime based on the active language server
rcasia/neotest-java pull request #124
Opened 2024-07-02 11:40 UTC by asmodeus812

2024-07-06 00:17 UTC, rcasia requested changes

2024-07-06 00:17 UTC, rcasia commented on lua/neotest-java/build_tool/gradle.lua
> +local grdl = require("neotest-java.command.binaries").gradle
Better to use the `gradle` instead of `grdl` as local variable name.

2024-07-06 00:17 UTC, rcasia commented on lua/neotest-java/command/runtime.lua
> +	local config = client.config.settings.java or {}
This is giving me this error. I suspect it is because I don't use any lsp settings. 
It also happens when I have no lsp client active.

In general, neotest-java should not relay in LSPs, they should be just a complement.

<details>
   Warn  01:25:56 AM notify.warn Neotest neotest-java: .../REPOS/neotest-java/lua/neotest-java/command/runtime.lua:19: attempt to index local 'client' (a nil value)
stack traceback:
	/home/rico/REPOS/neotest/lua/neotest/client/init.lua:89: in function '__index'
	.../REPOS/neotest-java/lua/neotest-java/command/runtime.lua:19: in function 'extract_runtime'
	.../REPOS/neotest-java/lua/neotest-java/command/runtime.lua:57: in function 'runtime'
	...REPOS/neotest-java/lua/neotest-java/build_tool/maven.lua:80: in function 'get_dependencies_classpath'
	...REPOS/neotest-java/lua/neotest-java/build_tool/maven.lua:97: in function 'prepare_classpath'
	...-java/lua/neotest-java/command/junit_command_builder.lua:128: in function 'build'
	...EPOS/neotest-java/lua/neotest-java/core/spec_builder.lua:88: in function 'build_spec'
	/home/rico/REPOS/neotest/lua/neotest/client/runner.lua:76: in function '_run_tree'
	/home/rico/REPOS/neotest/lua/neotest/client/runner.lua:65: in function </home/rico/REPOS/neotest/lua/neotest/client/runner.lua:22>
	[C]: in function 'xpcall'
	/home/rico/REPOS/neotest/lua/neotest/client/init.lua:84: in function 'run_tree'
	/home/rico/REPOS/neotest/lua/neotest/consumers/run.lua:73: in function 'func'
	/home/rico/REPOS/nvim-nio/lua/nio/tasks.lua:173: in function </home/rico/REPOS/nvim-nio/lua/nio/tasks.lua:172>

</details>

2024-07-06 00:17 UTC, rcasia commented on lua/neotest-java/command/runtime.lua
> +	local error, settings, client = lsp.execute_command({
`error` is a reserved keyword that holds the function to throw errors.

Better to replace it by `err` or something else.

2024-07-06 00:17 UTC, rcasia commented on lua/neotest-java/lsp/init.lua
> +						vim.sinepct(command.arguments)
`vim.sinepct` -> `vim.inspect`

2024-07-06 00:17 UTC, rcasia commented on lua/neotest-java/lsp/init.lua
> +local function execute_command(command, bufnr)
I would separate this two conditional branches into two different functions as their logic is unrelated and they are long blocks of code.

2024-07-06 00:17 UTC, rcasia commented on lua/neotest-java/lsp/init.lua
> +		local error = not ok and result ~= vim.NIL and { message = result } or nil
Better to replace it by `err` or something else.

2024-07-11 06:50 UTC, asmodeus812 commented
@rcasia could you take a look again, there are a few standing questions, regarding piping, extracting the bufnr and what do we do with gradle's runtime

2024-07-14 18:45 UTC, rcasia requested changes

2024-07-14 18:45 UTC, rcasia commented on lua/neotest-java/command/runtime.lua
I would not do this job here as the lsp should know what java executable to use using `vscode.java.resolveJavaExecutable` like in here: https://github.com/mfussenegger/nvim-jdtls/blob/6bfd1591583b02e742fc3a2f43393c4ea3b6d3c7/lua/jdtls/util.lua#L70

2024-07-14 18:45 UTC, rcasia commented on README.md
> +        java_runtimes = {
At least nvim-jdtls and coc-java already do this work. This seems like duplicate work as lsp could be already has this setting. Or am I missing something?

2024-07-14 18:45 UTC, rcasia commented on lua/neotest-java/util/read_xml_tag.lua
> +	-- why ? there are tags which can hold multiple tags / array of tags ?
I just wanted to retturn a non-table value, but feel free to use it to retrieve tables aswell.

2024-07-14 19:06 UTC, rcasia commented
With those changes it looks alright and ready to merge.

2024-07-15 06:12 UTC, asmodeus812 commented
> With those changes it looks alright and ready to merge.

Not yet, almost. There are a few things to iron out.

2024-10-06 16:29 UTC, rcasia commented
I will close this PR as #153 will fix the issue.

Thanks, this PR actually helped to get close to a solution.

2024-10-06 16:29 UTC, closed without merging

2024-10-07 14:34 UTC, asmodeus812 commented
@rcasia what about porting this to support coc, as the original pr ?

2024-10-07 18:10 UTC, rcasia commented
Responded in https://github.com/rcasia/neotest-java/issues/75#issuecomment-2397574152